fix: add updatePolicies
casbin/casbin.js pull request #202
Opened 2021-09-15 16:31 UTC by Gabriel-403

add updatePolicies

2021-09-16 00:59 UTC, Zxilly requested changes

2021-09-16 00:59 UTC, Zxilly commented on src/model/model.ts
> +    return [true, rules];
Should only return a boolean.

2021-09-16 00:59 UTC, Zxilly commented on src/persist/updatableAdapter.ts
> +  updatePolicies(sec: string, ptype: string, oldRule: string[][], newRule: string[][]): Promise<void>;
plz place this in batchAdapter Interface

2021-09-16 00:59 UTC, Zxilly commented on src/util/util.ts
> +  if (s.startsWith('r') || s.startsWith('p')) {
You should make another PR for these.

2021-12-21 16:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin/casbin.js?pullRequest=202) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin/casbin.js?pullRequest=202) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin/casbin.js?pullRequest=202) it.</sub>

2021-12-22 17:15 UTC, hsluoyz commented
@Gabriel-403

2021-12-23 05:15 UTC, closed without merging

2021-12-23 06:25 UTC, hsluoyz commented
@Gabriel-403 why close?